name: camera-cal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=>3.10
  - scons      # build management
  - libraw     # provides dcraw for RAW -> TIFF conversion
  - exiftool   # required to copy metadata from RAW -> TIFF
  - pyyaml     # for parsing yml settings files
  - imageio    # read images in python
  - piexif     # read image metadata in python
  - numpy      # numerical processing in python
  - scipy      # scientific function in python (including stats)
  - h5py       # read h5 files in python
  - numba      # accelerated numerical processing in python
  - scikit-learn # machine learning tools in python
  - xlsxwriter   # write excel files in python
  - matplotlib-base # create plots in python (-base variant does not include Qt gui)
  - sphinx      # for documentation
  - myst-parser # for documentation (Markdown support)
  - furo        # for documentation (site theme)
  - sphinx-copybutton # add "copy" button to code examples